### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by delta-kor** [okysky1121/qu-iz#13]
### Front End
- [x] Main page
  - [x] Http request
    - [x] User login flow
    - [x] Edit nickname
    - [x] User data
    - [x] Challenge list
    - [x] Ranking

### Back End
- [x] Add musics module
  - [x] Add song model
  - [x] Add album model
  - [x] Add controller
  - [x] Add service
- [x] Implement editing user data
- [x] Implement serving challenge lists
